name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ {"os": ubuntu-latest, short: linux},{"os": windows-latest, short: windows}]
        compiler: [gcc,clang]

    runs-on: ${{matrix.os.os}}

    steps:
    - uses: actions/checkout@v3

    - name: Add clang and and gcc to windows runner
      uses: msys2/setup-msys2@v2
      if: runner.os == 'Windows'
    
    - name: Configure CMake
      run: cmake --preset ${{matrix.os.short}}-${{matrix.compiler}}-release

    - name: Build
      run: cmake --build --preset ${{matrix.os.short}}-${{matrix.compiler}}-release
    
    - name: Test
      run: ctest --preset ${{matrix.os.short}}-${{matrix.compiler}}-release

